version: '3.8'

services:
  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGO_URL=mongodb+srv://vvm1004:test123@cluster0.4a2h5sc.mongodb.net/Cap2?retryWrites=true&w=majority&appName=Cluster
    expose:
      - 8080
    ports:
      - 8080:8080
