version: '3.8'

services:
  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - redis  

  redis:
    image: redis:7-alpine  
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
